### ISSUE TITLE
Does not work on ASTExplorer

### ISSUE THREAD

**Issue by pshrmn** [kentcdodds/babel-plugin-macros#102]
* `babel-plugin-macros` version: `2.4.2`+
* `node` version: `11.9.0`
* `npm` (or `yarn`) version: `1.13.0`

Relevant code or config

This commit (https://github.com/kentcdodds/babel-plugin-macros/commit/1785a0fab2c374d1505c49cff1bd38fd541819e2) added a dependency of the `resolve` module, which internally uses `fs`.

https://github.com/kentcdodds/babel-plugin-macros/blob/0048b14161b4e13068eea2b295e54df162193b19/src/index.js#L159

ASTExplorer uses Webpack's [`node`](https://webpack.js.org/configuration/node/#node) setting to shim `fs` with an empty object.

https://github.com/fkling/astexplorer/blob/8b30e3d79498804bedfda4d4c802538fe0c60f5e/website/webpack.config.js#L240

What you did:

Attempted to use an `import` in the code (top left box) section on ASTExplorer.

What happened:

An `i.statSync is not a function` error

Reproduction repository:

n/a

Problem description:

1. Go to [ASTExplorer](https://astexplorer.net/)
2. Activate the `babel-plugin-macros` transform
3. Add an `import` statement in the code (top left) section.

Suggested solution:

[`path.relative`](https://nodejs.org/docs/latest/api/path.html#path_path_relative_from_to)?

**Comment by kentcdodds** [comment]
The reason path.relative won't work is because we need it to resolve like a require would. Can't use require.resolve because we need it to be relative to the file being compiled 😟

I'm open to any suggestions! We may be able to add an option to allow some to specify their own module resolution function. I think we've done sobering like that in the past for astexplorer.net. Anyone want to work on that?
