### ISSUE TITLE
"Duplicate declaration" error due to identifier traversal change 

### ISSUE THREAD

**Issue by ben-rogerson** [kentcdodds/babel-plugin-macros#164]
Hey Kent 👋 

I'm experiencing an import issue in twin.macro that's popped up in the latest version of babel-plugin-macros (v3.0.0).

I've tracked [down the change](https://github.com/kentcdodds/babel-plugin-macros/compare/v2.8.0...v3.0.0#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R235
) that's caused the break and noticed it wasn't described in the change list:

```diff
- state.file.scope.path.traverse({
+ traverse(state.file.ast, {
    Identifier() {},
})
```

It breaks with the following error:

```shell
./pages/index.tsx
TypeError: /Users/.../pages/index.tsx: Duplicate declaration "_styled" (This is an error on an internal node. Probably an internal error.)
```

The error hints at something else due to twin having inserted another `styled-components/macro` import. (A macro adding another macro ha!)

Here's the [code that inserts the import in twin.macro](https://github.com/ben-rogerson/twin.macro/blob/master/src/macro/css.js#L70):

```js
twinImportPath.insertBefore(
    t.importDeclaration(
      [t.importDefaultSpecifier(generateUid('cssPropImport', program))],
      t.stringLiteral(styledComponentsMacroImport)
    )
)
```

Reference issue: https://github.com/ben-rogerson/twin.macro/issues/241

**Comment by conartist6** [comment]
Here's what I gathered up from looking at the changes you mentioned: The change was in [this PR](https://github.com/kentcdodds/babel-plugin-macros/pull/156). Which was made to solve [this issue](https://github.com/kentcdodds/babel-plugin-macros/issues/121). And the whole thing is commented as a hack to solve [this problem](https://github.com/kentcdodds/import-all.macro/issues/7).

And it wasn't just a noisy change that can be reverted because that change was the one that solved the other bug. So I guess we need to understand the root cause of #121 so that we can devise an alternate fix for it.

**Comment by conartist6** [comment]
I suspect what we're looking at is a regression of https://github.com/kentcdodds/import-all.macro/issues/7. The code that fixed the issue was rather magical, and according to the comment its intent was to do a traversal that would recompute scope. A stateless traversal of the ast alone would not recompute scope, making it pointless.

**Comment by conartist6** [comment]
So to distill it down, the problem that was being seen was that somehow this code:

```js
state.file.scope.path.traverse({
  Identifier() {},
})
```

Was causing a failure. It was never adequately investigated originally what the code would have interacted with to cause problems, but I'm pretty sure it must be something in [this file](https://github.com/styled-components/babel-plugin-styled-components/blob/e3829d28f2b460e097f1499f6091a52b667ef1b4/src/visitors/transpileCssProp.js#L124). In that file we have `const program = state.file.path`, so both bits of code are working with the same objects. Looking through the file for the usages of `program` these lines jump out:

https://github.com/styled-components/babel-plugin-styled-components/blob/e3829d28f2b460e097f1499f6091a52b667ef1b4/src/visitors/transpileCssProp.js#L118-L124

**Comment by conartist6** [comment]
As usual with babel the documentation consists of tweets: https://twitter.com/sebmck/status/1132038207309172736

**Comment by ben-rogerson** [comment]
Thanks so much for your fast response and epic digging Conrad 👍
