### ISSUE TITLE
Clarification on type of dependency.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [kentcdodds/babel-plugin-macros#53]
The documentation specifies that `babel-plugin-macros` [should be a devDependency](https://github.com/kentcdodds/babel-plugin-macros/blob/ec116e4e08ac7598d7e62046c81a91e51b0317bb/README.md#installation), but I cannot seem to find any mention of whether a macro should be a dependency or a devDependency.

Let's say I have an application `my-application` that depends on a package `my-package` that uses a macro `my.macro`.  When I publish `my-package`, it is transpiled, so `my-application` should not require `my.macro` or `babel-plugin-macros` to consume it.  Does this mean `my.macro` should be a devDependency of `my-package`?

**Comment by kentcdodds** [comment]
Great question. It actually doesn't matter that much for Frontend projects if you're bundling (for that matter, none of the dependencies are actually used in production, just the bundle, so all your dependencies could be Dev only).

For backend projects it should probably be dev because it is unnecessary in production (think of it like regular Babel plugins).

All this really depends though. I would suggest dev, because you shouldn't be running that code in production, only at build time. But in the worst case scenario, the only problem with listing it as a regular dep is installing it unnecessarily.

That's probably confusing, which is consistent with the fact that I've been lying in bed all day sick. 🤒😷🤧

I hope it's a little helpful though...

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you.  Would you like a PR adding this to the documentation?
```
But in the worst case scenario, the only problem with listing it as a regular dep is installing it unnecessarily.
```
Things like that keep me up at night.

**Comment by kentcdodds** [comment]
Yes please 👌 thanks!
