### ISSUE TITLE
Clarification on the kind of code that should be returned from a macro

### ISSUE THREAD

**Issue by hamlim** [kentcdodds/babel-plugin-macros#76]
* `babel-plugin-macros` version: `^2.0.0`
* `node` version: `v8.11.1`
* `npm` (or `yarn`) version: Yarn `1.9.2`

Not a direct issue with babel-plugin-macros, instead asking for clarification on what the returned value of a macro should look like if it returns javascript.

The title might not be that descriptive of the actual issue, but I couldn't find a better way to describe the question 😆.

Should macros return code that is expected to still be transformed by regular babel plugins, or should it return code that is consumer ready (i.e. transforming jsx down to createElement calls).

I am working on https://github.com/hamlim/inline-mdx.macro which transforms a string to a component that renders some JSX, so it currently transforms into something like this:

```jsx
const Component = ({ components }) => <MDXTag ...><div>{`Some Text`}</div></MDXTag>
```
(`...` on MDXTag is just omitting some other props)

Should this macro instead return something like:

```js
var Component = function(_ref) {
  var components = _ref.components;
  return React.createElement(MDXTag, { ... }, ...);
};
```

**Comment by kentcdodds** [comment]
Good question! This is a good general babel plugin question which Jamie Kyle answers pretty well here: https://jamie.build/babel-plugin-ordering.html

Luckily for us, macros are one of the first plugins called because it has to do with imports which will generally appear before anything else in the file. So your transforms will happen before most any other transform. In addition, if a user has multiple macros in a single file, they can control the order in which they're executed simply by changing the order in which they're imported which is a pretty sweet feature of macros :)

So to answer your specific question, you can transpile it as you are and you should be fine :)

If you'd like to write this up (or even just link to this) in the docs, I'd appreciate it!

**Comment by hamlim** [comment]
Thanks for the quick and in-depth response!
